# Copyright 2021 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html 

# This file use samei build process of
# https://github.com/openssl/openssl/blob/master/.github/workflows/windows.yml
# with the addition the Check executable version step
name: 'Openssl Windows compiler action'
description: 'Compiles the openssl from https://github.com/openssl/openssl to use openssl.exe as built-in executable on softwares that depends of it functionalities'

inputs:
  build-type:
    description: 'can be "plain" or "minimal"'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Install MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Clone openssl
      shell: pwsh
      run: git clone https://github.com/openssl/openssl.git

    - name: Prepare the build directory 
      shell: pwsh
      working-directory: openssl
      run: mkdir _build
    
    - name: Configure, build and test plain
      shell: pwsh
      working-directory: openssl/_build
      if: ${{ inputs.build-type == 'plain' }}
      run: | 
        perl ..\Configure --banner=Configured no-makedepend no-shared no-fips VC-WIN64A-masm
        perl configdata.pm --dump
        nmake /S
        nmake test VERBOSE_FAILURE=yes HARNESS_JOBS=4

    - name: Configure, build and test minimal
      shell: pwsh
      working-directory: openssl/_build
      if: ${{ inputs.build-type == 'minimal' }}
      run: |
        perl ..\Configure --banner=Configured no-makedepend no-bulk no-deprecated no-fips no-asm -DOPENSSL_SMALL_FOOTPRINT
        perl configdata.pm --dump
        nmake
        nmake test VERBOSE_FAILURE=yes TESTS=-test_fuzz* HARNESS_JOBS=4

    # Set environment variable in windows
    # https://www.jamescroft.co.uk/setting-github-actions-environment-variables-in-powershell/
    - name: Set openssl path dir
      id: set-output-dir
      shell: pwsh
      working-directory: openssl/apps
      run: |
        $opensslPath = Get-Location
        echo "BUILT_OPENSSL_PATH=$opensslPath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
