name: Setup the openssl folders

on:
  workflow_call:
    
    inputs:
      os: 
        description: The os to be used on this workflow
        type: string
        required: true
      rootdir:
        description: The root directory where the folders will be placed
        type: string
        required: true
      prefix-name:
        description: The name of the "prefix" folder
        type: string
        required: true
      openssldir-name:
        description: The name of the "openssl" folder
        type: string
        required: true
    
    outputs:
      prefix:
        description: The complete path of "prefix" folder
        value: ${{ jobs.setup.outputs.prefix }}
      openssldir:
        description: The complete path of "openssl" folder
        value: ${{ jobs.setup.outputs.openssldir }}

jobs:
  name: setup
  runs-on: ${{ inputs.os }}
  outputs: 
    prefix: ${{ steps.set-prefix.outputs.prefix }}
    openssldir: ${{ steps.set-openssldir.outputs.openssl }}

  steps:
    
    - id: set-prefix
      shell: pwsh
      run: echo "prefix=${{ inputs.rootdir }}\${{ inputs.prefix-name }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

    - id: set-openssldir
      shell: pwsh
      run: echo "openssldir=${{ inputs.rootdir }}\${{ inputs.openssldir-name }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

    - id: make-prefix
      shell: pwsh
      run: mkdir ${{ steps.set-prefix.outputs.prefix }}

    - id: make-openssldir
      shell: pwsh
      run: mkdir ${{ steps.set-openssldir.outputs.openssldir }}

