on: [push]

jobs:
  test:
    strategy:
      matrix:
        build-type:
          - plain
          - minimal
        os: 
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build openssl
        id: build
        uses: ./
        with:
          build-type: ${{ matrix.build-type }}

      - name: Check outputs
        shell: pwsh
        run: |
          echo "${{ steps.build.outputs.openssl-version }} is at ${{ steps.build.outputs.openssl-path-dir }}"

      - name: Test funtionality I: generate hex string
        shell: pwsh
        working-directory: ${{ steps.build.outputs.openssl-path-dir }}
        run: openssl.exe rand -hex 16

      - name: Test funtionality II: generate base64 string
        shell: pwsh
        working-directory: ${{ steps.build.outputs.openssl-path-dir }}
        run: openssl.exe rand -base64 16
