on: [push]

jobs:
  test-minimal:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build openssl on windows-latest
        uses: ./ # Uses an action in the root directory
        with:
          build-type: 'minimal'
