on: [push]

jobs:
  test:
    strategy:
      matrix:
        build-type:
          - plain
          - minimal
        os: 
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build openssl
        id: build
        uses: ./
        with:
          build-type: ${{ matrix.build-type }}

      - name: Test functionality I (get version)
        shell: pwsh
        run: ${{ steps.build.outputs.openssl-path-dir }}\openssl.exe version
      
      - name: Test functionality II (generate hex string)
        shell: pwsh
        run: ${{ steps.build.outputs.openssl-path-dir }}\openssl.exe rand -hex 16

      - name: Test functionality III (generate base64 string)
        shell: pwsh
        run: ${{ steps.build.outputs.openssl-path-dir }}\openssl.exe rand -base64 16
