on: [push]

jobs:
  test:
    strategy:
      matrix:
        build-type:
          - plain
          - minimal
        os: 
          - windows-latest

    runs-on: ${{ matrix.os }}

    outputs:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build openssl
        id: build
        uses: ./
        with:
          build-type: ${{ matrix.build-type }}

      - name: Check version
        shell: pwsh
        run: echo OPENSSL VERSION FROM TEST: ${{ steps.build.outputs.openssl-version }}

      - name: Check executable path
        shell: pwsh
        run: echo OPENSSL PATH FROM TEST: ${{ steps.build.outputs.openssl-path }}
